pipeline {
    agent any
    
    environment {
        AWS_REGION = 'ap-south-1'  // Adjust your region if necessary
    }

    stages {
        stage('Declarative: Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('Create Lambda Zip') {
            steps {
                script {
                    // List files inside the devopsexam2025 folder to confirm file exists
                    sh 'ls -l devopsexam2025'
                    
                    // Create the zip file from lambda_function.py in devopsexam2025 subfolder
                    sh 'zip -r lambda.zip devopsexam2025/lambda_function.py'
                }
            }
        }

        stage('TF Init') {
            steps {
                dir('devopsexam2025') {
                    script {
                        // Initialize Terraform
                        sh 'terraform init'
                    }
                }
            }
        }

        stage('TF Validate') {
            steps {
                dir('devopsexam2025') {
                    script {
                        // Validate Terraform configurations
                        sh 'terraform validate'
                    }
                }
            }
        }

        stage('TF Plan') {
            steps {
                dir('devopsexam2025') {
                    script {
                        // Run Terraform plan to see what changes will be made
                        sh 'terraform plan'
                    }
                }
            }
        }

        stage('TF Apply') {
            steps {
                dir('devopsexam2025') {
                    script {
                        // Apply the Terraform changes
                        sh 'terraform apply -auto-approve'
                    }
                }
            }
        }
    }
}
