pipeline {
    agent any
    
    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('TF Init') {
            steps {
                script {
                    dir('devopsexam2025') {
                        sh 'terraform init'
                    }
                }
            }
        }

        stage('TF Validate') {
            steps {
                script {
                    dir('devopsexam2025') {
                        sh 'terraform validate'
                    }
                }
            }
        }

        stage('TF Plan') {
            steps {
                script {
                    dir('devopsexam2025') {
                        sh 'terraform plan'
                    }
                }
            }
        }

        stage('TF Apply') {
            steps {
                script {
                    dir('devopsexam2025') {
                        sh 'terraform apply -auto-approve'
                    }
                }
            }
        }
        
        // Add any other stages for your Lambda invocation or other steps...
    }
}
